name: 11 - Working with inputs
description: "Demonstrating how to use inputs in GitHub Actions workflows"


on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Skiping deployment and print build output"'
                type: boolean
                default: true
            target:
                type: environment
                required: true
                description: 'Which environment the workflow will target'
            tag:
                type: choice
                description: 'Select the deployment tag'
                options:
                    - 'v1'
                    - 'v2'
                    - 'v3'
                default: 'v3'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
            echo "Building application from tab: ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: |
            echo "Deploying to ${{ inputs.target }}"