name: 14 - working with Artifacts
# udo npx create-react-app --template typescript react-app
on:
    workflow_dispatch:

env:
    build-artifact-key: app-${{  github.sha}}
    test-coverage-key: test-coverage-${{ github.sha}}

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts-folder/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setuo Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Download cache dependencies
              uses: actions/cache@v3
              id: cache-id
              with:
                path: 13-caching-folder/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-json') }}
            - name: Install dependencies
              if: steps.cache-id.outputs.cache-hit != 'true'
              run: npm ci
            - name: Testing
              run: npm run test -- --coverage
            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                    name: test-coverage-${{ env.test-coverage-key}}
                    path: 14-artifacts-folder/react-app/coverage

            - name: Build code
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: app-build-${{ env.build-artifact-key}} 
                    path: 14-artifacts-folder/react-app/build
            
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                    name: pp-build-${{ env.build-artifact-key}} 
                    path: build
            - name: Show folder structure
              run: |
                echo "Showing folder structure after downloading artifact..."
                ls -R build