name: 15-2 Working with Matrices

on:
    workflow_dispatch:


jobs:
   include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            color: [red, green]
            shape: [circle, square]
            size: [small, large]
            include:
                - color: red
                  shape: triangle

