name: 15-4 Working with Matrices setup

on:
    workflow_dispatch:


jobs:
    include-example:
      name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
      runs-on: ubuntu-latest
    
      strategy:
        matrix:
          color: [red, green]
          shape: [circle, square]
          size: [small, large]
          include:
            - opacity: 50
            - color: red
              shape: triangle
      
      steps:
        - name: Dummy Step # passo falso
          run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
  

