name: 15-4 Working with Matrices setup

on:
    workflow_dispatch:


jobs:
    include-example:
      name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
      runs-on: ubuntu-latest
    
      strategy:
        matrix:
          color: [red, green]
          shape: [circle, square]
          size: [small, large]
          include:
            - opacity: 111 
            - color: red  # tudo que tiver relacionado com red recebe 75
              opacity: 75
            - shape: circle # tudo que tiver relacionado com circulo recebe 100
              opacity: 100
            - color: red
              shape: triangle

      steps:
        - name: Dummy Step # passo falso
          run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"

          #red-circle-small-100
          #red-circle-large-100
          #red-square-small-75
          #red-square-large-75
          #green-circle-small-100
          #green-circle-large-100
          #green-square-small-111  - opacity: 111 
          #green-square-large-111
          #red-triangle--50
